name: Provision DMX Gatekeeper
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
      AzureTenantId: ${{ secrets.AZURE_TENANTID }}
      AzureAdAppProvisionClientId: ${{ secrets.AZURE_ADAPP_PROVISION_CLIENTID }}
      AzureAdAppProvisionClientSecret: ${{ secrets.AZURE_ADAPP_PROVISION_CLIENTSECRET }}
      AzureAdAppDmxGatekeeperClientId: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_CLIENTID }}
      AzureAdAppDmxGatekeeperInstance: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_INSTANCE }}
      AzureAdAppDmxGatekeeperDomain: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_DOMAIN }}
      AzureAdAppDmxGatekeeperCallbackPath: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_CALLBACKPATH }}
      AzureAdAppDmxGatekeeperScopesGetAllLabs: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_SCOPES_GETALLLABS }}
      AzureAdAppDmxGatekeeperScopesPostLab: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_SCOPES_POSTLAB }}
      AzureAdAppDmxCoreAppIdUri: ${{ secrets.AZURE_ADAPP_DMXCORE_APPIDURI }}
      AzureAdAppDmxCoreAppScopesGetAllLabs: ${{ secrets.AZURE_ADAPP_DMXCORE_APPSCOPES_GETALLLABS }}
      AzureAdAppDmxCoreAppScopesPostLab: ${{ secrets.AZURE_ADAPP_DMXCORE_APPSCOPES_POSTLAB }}
      AzureAppServiceDmxCoreApiUrl: ${{ secrets.AZURE_APPSERVICE_DMXCOREAPI_URL }}
      AzureAppServiceDmxCoreApiAccessKey: ${{ secrets.AZURE_APPSERVICE_DMXCOREAPI_ACCESSKEY }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Gatekeeper.Api.Infrastructure.Provision\DMX.Gatekeeper.Api.Infrastructure.Provision.csproj
